---
# deployment
# database stateful so 1 replica; if more, need one to be master and the rest be read-only
apiVersion: apps/v1
kind: Deployment
metadata:
    name: nwapp-deploy
    namespace: nw-ns
    labels:
        app: northwind
spec:
    replicas: 3
    selector:
        matchLabels:
            app: nwapp-northwind
    template:
        metadata:
            name: nwapp-po
            labels:
                app: nwapp-northwind
        spec:
            containers:
            -   name: nwapp-container
                image: stackupiss/northwind-app:v2
                imagePullPolicy: IfNotPresent
                env:
                -   name: DB_PASSWORD
                    valueFrom:
                      secretKeyRef:
                        name: nw-secret
                        key: MYSQL_ROOT_PASSWORD
                -   name: INSTANCE_IP_ADDRESS
                    valueFrom:
                      fieldRef:
                        fieldPath: status.podIP
                envFrom:
                -   configMapRef:
                        name: nwapp-cm
                ports:
                -   name: nwapp-port
                    containerPort: 3000