---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: nw-ns
  name: nwdb-pvc
  labels:
    app: northwind
    app.kubernetes.io/name: northwind
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: dobs.csi.digitalocean.com # standard label for provisioning tools to recognize for automation
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: do-block-storage
  resources:
    requests:
      # G - 1000MB, Gi - 1024MB
      storage: 1Gi