---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wpapp-cm
  labels:
    app: northwind
data:
    WORDPRESS_DB_USER: root
    WORDPRESS_DB_HOST: wp-db-cluster-mysql.wp.svc.cluster.local # FQDN
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wpapp-pvc
  labels:
    app: wordpress
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: do-block-storage
  resources:
    requests:
      # G - 1000MB, Gi - 1024MB
      storage: 1Gi
  volumeMode: Filesystem
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: wpapp-deploy
    labels:
        app: wordpress
spec:
    replicas: 1
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxSurge: 1
            maxUnavailable: 0
    selector:
        matchLabels:
            app: wordpress
    template:
        metadata:
            name: wpapp-po
            labels:
                app: wordpress
        spec:
            volumes: 
            - name: wpapp-vol
              persistentVolumeClaim:
                    claimName: wpapp-pvc
            containers:
            -   name: wpapp-container
                image: wordpress:latest
                imagePullPolicy: IfNotPresent
                volumeMounts:
                - name: wpapp-vol
                  mountPath: /var/www/html
                env:
                -   name: WORDPRESS_DB_PASSWORD
                    valueFrom:
                      secretKeyRef:
                        name: wp-secret
                        key: ROOT_PASSWORD
                -   name: INSTANCE_IP_ADDRESS
                    valueFrom:
                      fieldRef:
                        fieldPath: status.podIP
                envFrom:
                -   configMapRef:
                        name: wpapp-cm
                ports:
                -   name: wpapp-port
                    containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
    name: wpapp-svc
    labels:
        app: wprdpress
spec:
    type: ClusterIP
    selector:
        app: wordpress
    ports:
    -   name: wpapp-svc-port
        port: 80
        targetPort: wpapp-port
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
    name: wpapp-ing
    labels:
        app: wordpress
    annotations:
        nginx.ingress.kubernetes.io/limit-rps: "5"
spec:
    ingressClassName: nginx
    rules:
    - host: acme.167.172.5.17.nip.io
      http:
        paths:
        - path: /
          backend:
            serviceName: wpapp-svc
            servicePort: wpapp-svc-port
